server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_mv?useSSL=false&serverTimezone=UTC
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always